name: news_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #state_management
  flutter_bloc: ^8.1.2

  #comparing dart objects
  equatable: ^2.0.5

  #service_locator
  get_it: ^7.6.0

  #date_format
  intl: ^0.18.1

  #Database
  floor: ^1.4.2

  #make_API_request
  retrofit: ^3.0.1

  #Hooks
  flutter_hooks: ^0.18.3

  #Cached_images
  cached_network_image: ^3.2.0


dev_dependencies:

  flutter_test:
    sdk: flutter
  retrofit_generator: ^3.0.0+1
  floor_generator: ^1.2.0
  build_runner: ^2.1.2
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

